name: hagrad
channels:
  - apple
  - conda-forge
dependencies:
  - abseil-cpp=20210324.2
  - absl-py=0.10.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.2.0
  - blinker=1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cryptography=39.0.0
  - flatbuffers=1.12.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.15.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.39.1
  - grpcio=1.39.0
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - jpeg=9e
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - krb5=1.20.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libcxx=14.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libnghttp2=1.51.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.16.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libzlib=1.2.13
  - llvm-openmp=15.0.6
  - markdown=3.4.1
  - markupsafe=2.1.1
  - multidict=6.0.4
  - ncurses=6.3
  - numpy=1.19.5
  - oauthlib=3.2.2
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - pip=22.3.1
  - protobuf=3.16.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.6.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pyu2f=0.1.5
  - re2=2021.09.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.9.1
  - setuptools=65.6.3
  - six=1.15.0
  - snappy=1.1.9
  - sqlite=3.40.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-deps=2.5.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - tk=8.6.12
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2022g
  - urllib3=1.26.13
  - werkzeug=2.2.2
  - wheel=0.35.1
  - wrapt=1.12.1
  - xz=5.2.6
  - yarl=1.8.2
  - zipp=3.11.0
  - zlib=1.2.13